name: Ruby

on:
  push:
    branches:
      - "/**"

  pull_request:

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.0.6"
          - "3.1.4"
          - "3.2.2"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Nextify gem
        run: bundle exec rake nextify
      - name: Run the default task
        run: bundle exec rake
